//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18213
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Resources;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: AssemblyTitle("seth ver:0.9.30706.0")]
[assembly: AssemblyDescription("seth")]
[assembly: AssemblyProduct("seth")]
[assembly: AssemblyCopyright("Copyright (C) 2003-2013 Kody Brown.")]
[assembly: ComVisible(false)]
[assembly: CLSCompliant(false)]
[assembly: Guid("0F6C111B-9FE1-4828-BFCE-729E2CB8A012")]
[assembly: AssemblyVersion("0.9.30706.0")]
[assembly: AssemblyFileVersion("0.9.30706.0")]


